### ISSUE TITLE
Not signed in

### ISSUE THREAD

**Issue by travisnewman** [brandonplank/flappybird#11]
Installed OTA, there was never any indication that GameCenter was signing me in. Leaderboards show I’m not signed in as in the pic below 
![70F2CF6B-AFCC-4E83-B2CC-8ADCB75F104D](https://user-images.githubusercontent.com/3768622/93660707-a2c57080-fa1f-11ea-959c-a58557b77079.jpeg)

Edit: woooowwww I have no idea why this posted like 5 random pics from my phone before but if that shows up in the history, just blame some phone weirdness.

**Comment by brandonplank** [comment]
You have to sign in with google, click the google button...
