### ISSUE TITLE
How do I install the IPA for Apple Watch

### ISSUE THREAD

**Issue by LukasAppleFan** [brandonplank/flappybird#15]
This project seems very nice but how am I supposed to install the IPA on my Apple Watch as AltStore does not support watchOS.

**Comment by brandonplank** [comment]
Good question, or you can compile it with Xcode.

**Comment by brandonplank** [comment]
Just make sure your in the watchOS branch

**Comment by brandonplank** [comment]
I am actually about to just merge the two into a IPA. So when you sideload the iOS app, it should install on your watch.

**Comment by LukasAppleFan** [comment]
Oh ok nice thank you

**Comment by thomaboehi** [comment]
Hey! Very cool feature planned I would love to be able to play on my Watch 👌🏼

**Comment by HackZy01** [comment]
It’s impossible to sideload a Watch OS app without TestFlight or XCode
