### ISSUE TITLE
Latest Release CFBundleShortVersionString is incorrect.

### ISSUE THREAD

**Issue by noah978** [brandonplank/flappybird#2]
Hello,

I've been distributing your FlappyBird app to users of the AltStore Beta using my AltStore Source: [Quarksource](https://quarksources.imfast.io/)

I noticed on your most recent IPA the version should be 2.0 but the CFBundleShortVersionString (which AltStore uses for knowing when to push updates) is 1.0 instead.

``
<key>CFBundleShortVersionString</key>
``
``
<string>1.0</string>
``

Thanks!

**Comment by brandonplank** [comment]
Will fix now
