### ISSUE TITLE
"Needs to be updated" error with iOS 15 beta

### ISSUE THREAD

**Issue by iAdam1n** [brandonplank/flappybird#21]
Just wanted to let you know that this is broken on iOS 15 beta. Also wanted to say thanks so much for the great port!

**Comment by brandonplank** [comment]
Thanks for letting me know, i.m very sad to see that it does not work.

I actually do not have a mac/Hackintosh anymore, so i have no idea when i can push a fix. 

What exactly is broken and if it crashes, send a crash log.

**Comment by brandonplank** [comment]
It would be nice if someone could loan me a build machine for a day or two to fix this.

**Comment by iAdam1n** [comment]
Basically it just says what I said. I've attached a screenshot for you - happens when you try to open it. 
![IMG_0024](https://user-images.githubusercontent.com/2139641/121088604-e8101500-c7dd-11eb-9ff7-73ed5c55d058.jpeg)

**Comment by brandonplank** [comment]
Ok, i see. I will try and hackintosh my secondary machine in hopes of fixing this.

**Comment by iAdam1n** [comment]
Awesome! I did have an idea and wondered if just recompiling would work, but I don't have the pod files in the folder "Pods" - grabbed the whole repo just before I installed macOS 12 beta.

**Comment by brandonplank** [comment]
Hey, you can try. When you clone the repo, run pod install in the directory. 

Though, in this build you will not have Leaderboards or google login etc. that is in a private GitHub repo. I can probably get thatcher to re-compile it.

**Comment by iAdam1n** [comment]
Ah ok - I just figured maybe if you try recompiling on macOS 12 and with the iOS 15 beta SDK, it *might* work. Just a guess of course. If you want me to help with that in future, just let me know.

**Comment by brandonplank** [comment]
Update, I have successfully hackintoshed my secondary pc on Big Sur, I am installing the Xcode 13 beta now, expect fix to be released tonight!

**Comment by iAdam1n** [comment]
Amazing, thanks for being super swift with this!

**Comment by brandonplank** [comment]
Tested and published.

https://github.com/brandonplank/flappybird/releases/tag/3.9

Happy Flapping!

**Comment by burkybang** [comment]
Will you be updating it on your repo, repo.brandonplank.org, too?

**Comment by brandonplank** [comment]
I didn't even know my jailbreak repo was still up lol.Yeah I'll push it soon, I have no idea where I'm hosting that repo.

**Comment by burkybang** [comment]
Thanks! I like installing it from your repo more than sideloading it since it doesn't need to be resigned. Speaking of that, the current repo version (3.8) crashes at launch on iOS 14.3 for me. Should I create a new issue?

**Comment by brandonplank** [comment]
I have updated my jailbreak repo, you should now see an update! Also edited release to include the deb.

**Comment by brandonplank** [comment]
send crash logs, a video goes not help.

**Comment by brandonplank** [comment]
and more info like from where you installed it, and if you have app sync unified installed.

**Comment by iAdam1n** [comment]
I'm curious, how did you manage to install it on iOS 15 beta? I'm having Xcode say "Unable to install "Flappy Bird"", Cydia Impactor shows this below.
<img width="251" alt="Screenshot 2021-06-08 at 23 16 09" src="https://user-images.githubusercontent.com/2139641/121267524-37c11000-c8b4-11eb-81b2-1ed515809cf6.png">

**Comment by brandonplank** [comment]
> I'm curious, how did you manage to install it on iOS 15 beta? I'm having Xcode say "Unable to install "Flappy Bird"", Cydia Impactor shows this below.
> 
> <img width="251" alt="Screenshot 2021-06-08 at 23 16 09" src="https://user-images.githubusercontent.com/2139641/121267524-37c11000-c8b4-11eb-81b2-1ed515809cf6.png">
> 
> 

I'm pretty sure iOS 15 broke code signing for all side loaded apps.

**Comment by iAdam1n** [comment]
Yeah I saw that after I posted here, thanks. I guess you tested by compiling and running from Xcode.

**Comment by brandonplank** [comment]
Yeah

**Comment by iAdam1n** [comment]
Is there any chance of sharing the full code (private repo) with me so I can build it fully with Xcode? Based on what Apple are saying on sideloading, I don't believe that they broke it by accident and that it'll stay that way.

**Comment by brandonplank** [comment]
Unfortunately no, but I will share a method to side load the ipa with Xcode itself.

**Comment by brandonplank** [comment]
You can always compile this repo as it is almost the exact same gameplay wise, just no leaderboards, sign in, etc.

**Comment by iAdam1n** [comment]
Ok thanks.

**Comment by iAdam1n** [comment]
Hm, now I get the following and not really finding anything for it on Google:

<unknown>:0: error: module map file '/Users/iAdam1n/Library/Developer/Xcode/DerivedData/Flappy_Bird-cbpvaxgpymaywddcylwcjrsqnors/Build/Products/Release-iphoneos/Then/Then.modulemap' not found
/Users/iAdam1n/Downloads/flappybird/Flappy Bird/GameViewController.swift:13:8: error: no such module 'Then'
import Then
