### ISSUE TITLE
Couldn't be saved

### ISSUE THREAD

**Issue by Roshanxy** [brandonplank/flappybird#22]
Hi
I'd like to sideload it with altstore but I receive the following error:

The file "UIViewController-BV1-FR-VrT.nib" couldn't be saved in the folder "Main.storyboardc".

Altstore 1.4.5, iOS 14.6 and the latest app release with iOS 15 support

**Comment by Roshanxy** [comment]
Perhaps it's because of this:
https://twitter.com/altstoreio/status/1404564607428030464
But I am on iOS 14

**Comment by brandonplank** [comment]
Alt stores has to be updated.

The update is out only for patrons.
