### ISSUE TITLE
No sound on Speakers

### ISSUE THREAD

**Issue by jaydengamble6** [brandonplank/flappybird#23]
Every time I launch the game there's no sound unless I plug in my headphones then I can hear all the sound effects.

I'm using an IPhone 11 on iOS 14.7.

**Comment by brandonplank** [comment]
I have no idea what could cause this. If there was logs, I could tell, but unless there are logs, I cannot do anything.

**Comment by jaydengamble6** [comment]
@brandonplank Where would I find the logs if they're are any?

**Comment by brandonplank** [comment]
Make sure your ringer switch is turned off lol

**Comment by jaydengamble6** [comment]
Oh its that sorry lmao, I switched to iPhone recently and I forgot how some apps are muted when you put it on Silent.
