### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by wbbrown56** [BrandonPlank/flappybird#24]
I am getting an error installing the IPA using both Sideloadly and the native IPA installer
<img width="262" alt="Screen Shot 2021-09-27 at 7 56 03 AM" src="https://user-images.githubusercontent.com/80070161/134912668-533dbd90-0696-44e6-b07a-3905b2e745af.png">
<img width="583" alt="Screen Shot 2021-09-27 at 7 56 34 AM" src="https://user-images.githubusercontent.com/80070161/134912692-3dfc10bc-55ec-45f6-afa3-3b04fc1b5278.png">
r.

**Comment by BrandonPlank** [comment]
Are you on macOS silicon?

If so try renaming the ipa to .zip and extract it then launch the .app inside

**Comment by wbbrown56** [comment]
That worked!

**Comment by BrandonPlank** [comment]
Cool! Note the server is currently down, but i am working on bringing it back up.

**Comment by BrandonPlank** [comment]
Server is up! Try signing up.

**Comment by BrandonPlank** [comment]
Yep! Your scores are being submitted!

``` json
{"deaths":2,"name":"wbbrown","score":5,"id":"87EF58C5-6933-4872-BAE4-D6E8E25D792F"}]
```

**Comment by BrandonPlank** [comment]
I have actually not even tested on the M1 chip. So i am surprised it even worked.

**Comment by wbbrown56** [comment]
Glad everything works. One request if possible is to be able to use the space bar to jump instead of clicking the trackpad.

**Comment by BrandonPlank** [comment]
Can you do me a favor and see if J works to jump?

**Comment by BrandonPlank** [comment]
If it does I can just change it to space

**Comment by wbbrown56** [comment]
J is not working for me

**Comment by BrandonPlank** [comment]
Open an issue so I don't forget

**Comment by wbbrown56** [comment]
Got it
