### ISSUE TITLE
Space Bar to Jump

### ISSUE THREAD

**Issue by wbbrown56** [BrandonPlank/flappybird#25]
I am unable to use the space bar to jump, only the trackpad works currently.

**Comment by wbbrown56** [comment]
I do not see the beta to test

**Comment by BrandonPlank** [comment]
https://t.co/ftFUpeqJGw

**Comment by BrandonPlank** [comment]
Btw the ipa should install now

**Comment by wbbrown56** [comment]
The IPA still gave me the error but I was still able to do the .zip method. The space bar did not work for jumping.

**Comment by BrandonPlank** [comment]
Does the leaderboard work?

**Comment by BrandonPlank** [comment]
ok. i guess i have to make a new project that supports all platforms... ugg this is going to take a bit.

**Comment by wbbrown56** [comment]
Just take your time. The space bar thing was just a suggestion. Other than that the app works great!

**Comment by BrandonPlank** [comment]
Ok, it is jankey, but it works

Release : https://github.com/BrandonPlank/flappybird/releases/tag/4.0-beta-4-all

Spacebar only workings after you press Tap Tap for some reason.
