### ISSUE TITLE
Passwords are stored in plain text

### ISSUE THREAD

**Issue by vXtreniusX** [BrandonPlank/flappybird#26]
It looks like that the passwords aren’t protected at all in the preference file.

You can’t change the password to the account as well.

**Comment by BrandonPlank** [comment]
I am not even close to a full release. I am working on encrypting everything, i already have encrypted score submission, and the password change will come a few days before the release.

**Comment by BrandonPlank** [comment]
Also as a note, even through your passwords are sent to the server, the never reach the core server as they are transferred through middleware. 

The passwords are stored on the server as BCrypt hashes, you can see this whenever you POST request to https://flappybird.brandonplank.org/login with a basic auth header (your username and password) and you can see your private user structure returned inside of a JSON response.

**Comment by BrandonPlank** [comment]
Ok, fixed in my private build. Releasing shortly, regarding password reset, make a new issue.

**Comment by BrandonPlank** [comment]
![Screen Shot 2021-09-28 at 1 08 21 PM](https://user-images.githubusercontent.com/52553007/135538239-b1c18830-c57f-4b9f-8f4e-3b37dd19807d.png)

**Comment by BrandonPlank** [comment]
![Screen Shot 2021-09-30 at 6 26 12 PM](https://user-images.githubusercontent.com/52553007/135538259-24ed58e4-8ebb-420b-9f5b-a619de75562c.png)
