### ISSUE TITLE
Can’t log in

### ISSUE THREAD

**Issue by burkybang** [BrandonPlank/flappybird#27]
Ever since 4.0 Beta 7 or 8, I can't log in anymore. I have special characters in my password, and I saw you said something about encryption changing. I don’t know if those could be related.

Whether there's an issue or not, could I get my password changed somehow?

**Comment by BrandonPlank** [comment]
Well i wiped the database. Create a new account.

**Comment by BrandonPlank** [comment]
Message here you old score and ill re-add it.

**Comment by burkybang** [comment]
Oh that makes sense. I just recreated my account. My high score was 51. Username burkybang

**Comment by BrandonPlank** [comment]
Yeah, you seem to be good on the database.
