### ISSUE TITLE
Suggestion, not an issue.

### ISSUE THREAD

**Issue by Va1a** [brandonplank/flappybird#4]
There was a cool viral video from 2014 or so when the original game was popular displaying a cool “ending” to flappy bird once you reach the 1000 mark. I thought that if you guys had the time- as i’m sure scripting this would take a while- you could perhaps implement it? 

Footage of what it might look like:
https://youtu.be/4G5_AhbQ2mw 

Or, maybe just add certain aspects of it to make the game harder? Perhaps a hidden difficult mode which is unlocked once you reach the score of 100?

**Comment by brandonplank** [comment]
We already have an Easter egg at pipe 1000, and we are adding something at a further pipe in the near future!

**Comment by Va1a** [comment]
Haha cool, thanks- will try to achieve it!
