### ISSUE TITLE
Hello can I distribute it on a Cydia source

### ISSUE THREAD

**Issue by 1333481** [brandonplank/flappybird#6]
I will credit

**Comment by brandonplank** [comment]
No, official sources only.

**Comment by 1333481** [comment]
Nvm I saw the license is mit

**Comment by bonexd** [comment]
tfw you get told not to do it but you do it anyways
https://smallbossrepo.github.io/depiction/web/io.smallboss.flappybird.html

**Comment by 1333481** [comment]
> tfw you get told not to do it but you do it anyways
> 
> https://smallbossrepo.github.io/depiction/web/io.smallboss.flappybird.html
> 
> (smallboss being 1333481s repo)

Haha! It's MIT license
