### ISSUE TITLE
Physics are a bit off compared to the original

### ISSUE THREAD

**Issue by sidnoway** [brandonplank/flappybird#8]
It's hard to explain, but you can probably see it [in this video](https://www.youtube.com/watch?v=h98dPuxcTfg)

**Comment by ThatcherDev** [comment]
yes they are off a little but this was intentional. we decided to keep make them a little different so that it was easier to reach the lowest possible pipe from the highest possible pipe.

**Comment by sidnoway** [comment]
Could this possibly be changed as a toggle?

**Comment by travisnewman** [comment]
I know this is wontfix’d but just wanted to add, this makes that one condition easier but causes everything else to be a little trickier because of how easy job fall.
